/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package data.UI;

/**
 *
 * @author Luiiz
 */
public class Principal extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        Welcome = new javax.swing.JLabel();
        Welcome1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/utils/RP-med.png"))); // NOI18N
        add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 138, 680, 360));

        Welcome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Welcome.setForeground(new java.awt.Color(51, 51, 51));
        Welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome.setText("Agenda una cita, recogeremos tus residuos y obtendrás puntos ;)");
        add(Welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 680, -1));

        Welcome1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Welcome1.setForeground(new java.awt.Color(51, 51, 51));
        Welcome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome1.setText("¡Bienvenidos/as al centro de recolección de residuos RePlanet!");
        add(Welcome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 670, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Welcome;
    private javax.swing.JLabel Welcome1;
    // End of variables declaration//GEN-END:variables
}
